version: '3'

services:
    web-api:
        build:
            dockerfile: Dockerfile.development
        ports:
            - "5000:5000"
        volumes:
            - ./web-api/python/:/var/www

    web-gui:
        build:
            dockerfile: Dockerfile.development
        links:
            - web-api
        ports:
            - "80:80"
        volumes:
            - ./logs:/var/log/nginx
