FROM python:3.7.4

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

WORKDIR /var/www/
COPY ./python/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "application.py"]
